fasta: /cvmfs/softdrive.nl/projectmine_sw/resources/Build38/hs38DH/hs38DH.fa
dbSNP: /cvmfs/softdrive.nl/projectmine_sw/resources/Build38/hs38DH/dbsnp_146.hg38.vcf.gz
Mills: /cvmfs/softdrive.nl/projectmine_sw/resources/Build38/hs38DH/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
KnownIndels: /cvmfs/softdrive.nl/projectmine_sw/resources/Build38/hs38DH/Homo_sapiens_assembly38.known_indels.vcf.gz
tgt: /cvmfs/softdrive.nl/projectmine_sw/resources/Build38/hs38DH/cds_100bpSplice_utr_codon_mirbase.bed
list_of_files: "resources/minitest.list"
fasta_input: /cvmfs/softdrive.nl/projectmine_sw/resources/Build37/hg19/ucsc.hg19.fasta
# use the original code of pipeline
original : False
